# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0002_gig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='statuc',
            new_name='status',
        ),
    ]
